<?php

$fields =  array(
	'key' => 'layout_blog_subscribe_sidebar_'.$posttype,
	'name' => 'blog_subscribe_sidebar_'.$posttype,
	'label' => 'Blog Subscribe Sidebar',
	'display' => 'block',
	'sub_fields' => array(
		// BACKGROUND TAB
		array(
			'key' => 'field_blog_subscribe_sidebar_bg_options_tab_'.$posttype,
			'label' => 'Background Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_blog_subscribe_sidebar_bg_options_'.$posttype,
			'label' => 'Background Options',
			'name' => 'blog_subscribe_sidebar_bg_options',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_blog_subscribe_sidebar_bg_type_'.$posttype,
					'label' => 'Background Type',
					'name' => 'background_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'color' => 'Solid Color',
						'image' => 'Background Image',
						'video' => 'Background Video',
					),
					'default_value' => array(
						'color' => 'Solid Color',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_blog_subscribe_sidebar_bg_img_'.$posttype,
					'label' => 'Background Image',
					'name' => 'blog_subscribe_sidebar_bg_img',
					'type' => 'image_crop',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_blog_subscribe_sidebar_bg_type_'.$posttype,
								'operator' => '==',
								'value' => 'image',
							),
						),
						array(
							array(
								'field' => 'field_blog_subscribe_sidebar_bg_type_'.$posttype,
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'crop_type' => 'hard',
					'target_size' => 'ex-large',
					'width' => '',
					'height' => '',
					'preview_size' => 'thumbnail',
					'force_crop' => 'yes',
					'save_in_media_library' => 'yes',
					'retina_mode' => 'no',
					'save_format' => 'object',
					'library' => 'all',
				),
				array(
					'key' => 'field_blog_subscribe_sidebar_background_video_mp4_'.$posttype,
					'label' => 'Background Video .mp4',
					'name' => 'background_video_mp4',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_blog_subscribe_sidebar_bg_type_'.$posttype,
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
				array(
					'key' => 'field_blog_subscribe_sidebar_bg_color',
					'label' => 'Background Color',
					'name' => 'blog_subscribe_sidebar_bg_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_blog_subscribe_sidebar_text_color_'.$posttype,
					'label' => 'Text Color',
					'name' => 'blog_subscribe_sidebar_text_color',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'white' => 'Light',
						'black' => 'Dark',
					),
					'default_value' => array(
						0 => 'black',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_blog_subscribe_sidebar_bg_parallax_'.$posttype,
					'label' => 'Parallax',
					'name' => 'bg_parallax',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_blog_subscribe_sidebar_bg_type_'.$posttype,
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'no-parallax' => 'Parallax Off',
						'parallax' => 'Parallax On',
					),
					'default_value' => array(
						0 => 'no-parallax',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_blog_subscribe_sidebar_bg_parallax_speed_'.$posttype,
					'label' => 'Parallax Speed',
					'name' => 'bg_parallax_speed',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_blog_subscribe_sidebar_bg_parallax_'.$posttype,
								'operator' => '==',
								'value' => 'parallax',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'3' => 'Fastest',
						'2' => 'Fast',
						'1' => 'Normal',
						'0.5' => 'Slow',
						'0.25' => 'Slowest',
					),
					'default_value' => array(
						'1' => 'Slow',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_blog_subscribe_sidebar_text_padding_top_'.$posttype,
					'label' => 'Padding Top',
					'name' => 'blog_subscribe_sidebar_text_padding_top',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						0 => '0',
						1 => '1',
						2 => '2',
						3 => '3',
						4 => '4',
					),
					'default_value' => array(
						1 => '1',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_blog_subscribe_sidebar__text_padding_bot_'.$posttype,
					'label' => 'Padding Bottom',
					'name' => 'blog_subscribe_sidebar_text_padding_bot',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						0 => '0',
						1 => '1',
						2 => '2',
						3 => '3',
						4 => '4',
					),
					'default_value' => array(
						1 => '1',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_blog_subscribe_sidebar_block_settings_'.$posttype,
			'label' => 'Block Content',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_blog_subscribe_sidebar_hs_form_'.$posttype,
			'label' => 'Choose Form',
			'name' => 'hs_form',
			'type' => 'post_object',
			'post_type' => 'hs-form',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'allow_null' => 0,
			'multiple' => 0,
		),
			array(
					'key' => 'field_blog_subscribe_sidebar_headline_'.$posttype,
					'label' => 'Blog Subscribe Headline',
					'name' => 'blog_subscribe_sidebar_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),

				array(
						'key' => 'field_blog_subscribe_sidebar_cta_text_'.$posttype,
						'label' => 'Blog Subscribe CTA Text',
						'name' => 'blog_subscribe_sidebar_cta_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '75',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
	),
	'min' => '',
	'max' => '',
);

 ?>
