<?php
$fields =  array(
	'key' => 'layout_marquee_title_'.$posttype,
	'name' => 'marquee_title_'.$posttype,
	'label' => 'Marquee Page Title/ Breadcrumbs',
	'display' => 'block',
	'sub_fields' => array(
		array(
			'key' => 'field_marquee_title_image_'.$posttype,
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 1,
		),

		array(
			'key' => 'field_marquee_title_content_'.$posttype,
			'label' => '',
			'name' => 'content',
			'type' => 'group',
			'sub_fields' => array(
				array(
		      'key' => 'field_marquee_title_headline_'.$posttype,
		      'label' => 'Headline',
		      'name' => 'headline',
		      'type' => 'text',
		      'instructions' => '',
		      'required' => 0,
		      'conditional_logic' => 0,
		      'wrapper' => array(
		        'width' => '75',
		        'class' => '',
		        'id' => '',
		      ),
		      'default_value' => '',
		      'placeholder' => '',
		      'prepend' => '',
		      'append' => '',
		      'maxlength' => '',
		    ),
		    array(
		      'key' => 'field_marquee_title_size_'.$posttype,
		      'label' => 'Size',
		      'name' => 'size',
		      'type' => 'select',
		      'choices' => array(
		        'compact' => 'Compact',
		        'expanded' => 'Expanded',
		      ),
		      'instructions' => '',
		      'required' => 0,
		      'conditional_logic' => 0,
		      'wrapper' => array(
		        'width' => '25',
		        'class' => '',
		        'id' => '',
		      ),
		      'default_value' => '',
		      'placeholder' => '',
		      'prepend' => '',
		      'append' => '',
		      'maxlength' => '',
		    ),
		    array(
		      'key' => 'field_marquee_title_text_'.$posttype,
		      'label' => 'Line text',
		      'name' => 'text',
		      'type' => 'textarea',
		      'rows' => '4',
		      'instructions' => '',
		      'required' => 0,
		      'conditional_logic' => array(
		        array(
		          'field' => 'field_marquee_title_size_'.$posttype,
		          'operator' => '==',
		          'value' => 'expanded',
		        ),
		      ),
		      'wrapper' => array(
		        'width' => '',
		        'class' => '',
		        'id' => '',
		      ),
		      'default_value' => '',
		      'tabs' => 'all',
		      'toolbar' => 'full',
		      'media_upload' => 1,
		      'delay' => 1,
		    ),
		    array(
		      'key' => 'field_marquee_title_button_text_'.$posttype,
		      'label' => 'Button Text',
		      'name' => 'button_text',
		      'type' => 'text',
		      'instructions' => '',
		      'required' => 0,
		      'conditional_logic' => 0,
		      'wrapper' => array(
		        'width' => '35',
		        'class' => '',
		        'id' => '',
		      ),
		      'default_value' => '',
		      'tabs' => 'all',
		      'toolbar' => 'full',
		      'media_upload' => 1,
		      'delay' => 1,
		    ),
		    array(
		      'key' => 'field_marquee_title_button_link_'.$posttype,
		      'label' => 'Button Link',
		      'name' => 'button_link',
		      'type' => 'link',
		      'instructions' => '',
		      'required' => 0,
		      'conditional_logic' => 0,
		      'wrapper' => array(
		        'width' => '40',
		        'class' => '',
		        'id' => '',
		      ),
		      'default_value' => '',
		      'tabs' => 'all',
		      'toolbar' => 'full',
		      'media_upload' => 1,
		      'delay' => 1,
		    ),
		    array(
		      'key' => 'field_marquee_title_breadcrumbs_'.$posttype,
		      'label' => 'Breadcrumbs',
		      'name' => 'breadcrumbs',
		      'type' => 'select',
		      'choices' => array(
		        'show' => 'Show',
		        'hide' => 'Hide',
		      ),
		      'instructions' => '',
		      'required' => 0,
		      'conditional_logic' => 0,
		      'wrapper' => array(
		        'width' => '25',
		        'class' => '',
		        'id' => '',
		      ),
		      'default_value' => 'show',
		      'placeholder' => '',
		      'prepend' => '',
		      'append' => '',
		      'maxlength' => '',
		    ),
			),
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '66',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),



	),
	'min' => '',
	'max' => '',
);

//return $fields;
?>
