<?php
$fields =  array(
	'key' => 'layout_partner_logo_grid_'.$posttype,
	'name' => 'partner_logo_grid_'.$posttype,
	'label' => 'Partners Logo Grid',
	'display' => 'block',
	'sub_fields' => array(
			array(
				'key' => 'field_partner_logo_grid_block_settings_'.$posttype,
				'label' => 'Block Content',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_partner_logo_grid_groups_'.$posttype,
				'label' => 'Logos',
				'name' => 'partner_logo_grid_groups',
				'type' => 'repeater',
        'min' => '1',
				'button_label' => '+ Add Group',
				'sub_fields' => array(
					array(
						'key' => 'field_partner_logo_grid_headline_'.$posttype,
						'label' => 'Group Headline',
						'name' => 'group_headline',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'placeholder' => '',
					),
					array(
						'key' => 'field_partner_logo_grid_relationship_'.$posttype,
						'label' => 'Choose Partners for this Group',
						'name' => 'partners',
						'type' => 'relationship',
						'post_type' => 'partner',
						'instructions' => 'Choose the partner logos you want to display',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'partner',
						),
						'taxonomy' => '',
						'filters' => array('search'),
						'elements' => '',
						'min' => '',
						'max' => '',
						'return_format' => 'id',
					),
				),
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'layout' => 'block',
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
      	'key' => 'field_partner_logo_grid_bg_options_tab_'.$posttype,
      	'label' => 'Background Options',
      	'name' => '',
      	'type' => 'tab',
      	'instructions' => '',
      	'required' => 0,
      	'conditional_logic' => 0,
      	'wrapper' => array(
      		'width' => '',
      		'class' => '',
      		'id' => '',
      	),
      	'placement' => 'top',
      	'endpoint' => 0,
      ),
			array(
				'key' => 'field_partner_logo_grid_text_padding_top_'.$posttype,
				'label' => 'Padding Top',
				'name' => 'padding_top',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					0 => '0',
					1 => '1',
					2 => '2',
					3 => '3',
					4 => '4',
				),
				'default_value' => array(
					1 => '1',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_partner_logo_grid_text_padding_bot_'.$posttype,
				'label' => 'Padding Bottom',
				'name' => 'padding_bot',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					0 => '0',
					1 => '1',
					2 => '2',
					3 => '3',
					4 => '4',
				),
				'default_value' => array(
					1 => '1',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
	),
	'min' => '',
	'max' => '',
);

//return $fields;
?>
