<?php

$fields =  array(
	'key' => 'layout_events_upcoming_'.$posttype,
	'name' => 'events_upcoming_'.$posttype,
	'label' => 'Events - Upcoming',
	'display' => 'block',
	'sub_fields' => array(
    array(
        'key' => 'field_events_upcoming_headline_'.$posttype,
        'label' => 'Events Headline',
        'name' => 'events_upcoming_headline',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_events_upcoming_content_tab_'.$posttype,
        'label' => 'Block Content',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
			array(
				'key' => 'field_events_upcoming_'.$posttype,
				'label' => 'Upcoming Events',
				'name' => 'upcoming-events',
				'type' => 'html',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
      array(
      	'key' => 'field_events_upcoming_bg_options_tab_'.$posttype,
      	'label' => 'Background Options',
      	'name' => '',
      	'type' => 'tab',
      	'instructions' => '',
      	'required' => 0,
      	'conditional_logic' => 0,
      	'wrapper' => array(
      		'width' => '',
      		'class' => '',
      		'id' => '',
      	),
      	'placement' => 'top',
      	'endpoint' => 0,
      ),
  		array(
  			'key' => 'field_events_upcoming_bg_options_'.$posttype,
  			'label' => 'Background Options',
  			'name' => 'events_upcoming_bg_options',
  			'type' => 'group',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'layout' => 'block',
  			'sub_fields' => array(
  				array(
  					'key' => 'field_events_upcoming_bg_type_'.$posttype,
  					'label' => 'Background Type',
  					'name' => 'background_type',
  					'type' => 'select',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'choices' => array(
  						'color' => 'Solid Color',
  						'image' => 'Background Image',
  					),
  					'default_value' => array(
  						'color' => 'Solid Color',
  					),
  					'allow_null' => 0,
  					'multiple' => 0,
  					'ui' => 0,
  					'return_format' => 'value',
  					'ajax' => 0,
  					'placeholder' => '',
  				),
  				array(
  					'key' => 'field_events_upcoming_bg_img_'.$posttype,
  					'label' => 'Background Image',
  					'name' => 'events_upcoming_bg_img',
  					'type' => 'image',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => array(
  						array(
  							array(
  								'field' => 'field_events_upcoming_bg_type_'.$posttype,
  								'operator' => '==',
  								'value' => 'image',
  							),
  						),
  						array(
  							array(
  								'field' => 'field_events_upcoming_bg_type_'.$posttype,
  								'operator' => '==',
  								'value' => 'video',
  							),
  						),
  					),
  					'wrapper' => array(
  						'width' => '25',
  						'class' => '',
  						'id' => '',
  					),
  					'crop_type' => 'hard',
  					'target_size' => 'ex-large',
  					'width' => '',
  					'height' => '',
  					'preview_size' => 'thumbnail',
  					'force_crop' => 'yes',
  					'save_in_media_library' => 'yes',
  					'retina_mode' => 'no',
  					'save_format' => 'object',
  					'library' => 'all',
  				),
  				array(
  					'key' => 'field_events_upcoming_bg_color',
  					'label' => 'Background Color',
  					'name' => 'events_upcoming_bg_color',
  					'type' => 'color_picker',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '25',
  						'class' => '',
  						'id' => '',
  					),
  					'default_value' => '',
  				),
  				array(
  					'key' => 'field_events_upcoming_bg_parallax_'.$posttype,
  					'label' => 'Parallax',
  					'name' => 'bg_parallax',
  					'type' => 'select',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => array(
  						array(
  							array(
  								'field' => 'field_events_upcoming_bg_type_'.$posttype,
  								'operator' => '==',
  								'value' => 'image',
  							),
  						),
  					),
  					'wrapper' => array(
  						'width' => '25',
  						'class' => '',
  						'id' => '',
  					),
  					'choices' => array(
  						'no-parallax' => 'Parallax Off',
  						'parallax' => 'Parallax On',
  					),
  					'default_value' => array(
  						0 => 'no-parallax',
  					),
  					'allow_null' => 0,
  					'multiple' => 0,
  					'ui' => 0,
  					'return_format' => 'value',
  					'ajax' => 0,
  					'placeholder' => '',
  				),
  				array(
  					'key' => 'field_events_upcoming_bg_parallax_speed_'.$posttype,
  					'label' => 'Parallax Speed',
  					'name' => 'bg_parallax_speed',
  					'type' => 'select',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => array(
  						array(
  							array(
  								'field' => 'field_events_upcoming_bg_parallax_'.$posttype,
  								'operator' => '==',
  								'value' => 'parallax',
  							),
  						),
  					),
  					'wrapper' => array(
  						'width' => '25',
  						'class' => '',
  						'id' => '',
  					),
  					'choices' => array(
  						'3' => 'Fastest',
  						'2' => 'Fast',
  						'1' => 'Normal',
  						'0.5' => 'Slow',
  						'0.25' => 'Slowest',
  					),
  					'default_value' => array(
  						'1' => 'Slow',
  					),
  					'allow_null' => 0,
  					'multiple' => 0,
  					'ui' => 0,
  					'return_format' => 'value',
  					'ajax' => 0,
  					'placeholder' => '',
  				),
  				array(
  					'key' => 'field_events_upcoming_text_padding_top_'.$posttype,
  					'label' => 'Padding Top',
  					'name' => 'events_upcoming_text_padding_top',
  					'type' => 'select',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '33',
  						'class' => '',
  						'id' => '',
  					),
  					'choices' => array(
  						0 => '0',
  						1 => '1',
  						2 => '2',
  						3 => '3',
  						4 => '4',
  					),
  					'default_value' => array(
  						1 => '1',
  					),
  					'allow_null' => 0,
  					'multiple' => 0,
  					'ui' => 0,
  					'return_format' => 'value',
  					'ajax' => 0,
  					'placeholder' => '',
  				),
  				array(
  					'key' => 'field_events_upcoming_text_padding_bot_'.$posttype,
  					'label' => 'Padding Bottom',
  					'name' => 'events_upcoming_text_padding_bot',
  					'type' => 'select',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '33',
  						'class' => '',
  						'id' => '',
  					),
  					'choices' => array(
  						0 => '0',
  						1 => '1',
  						2 => '2',
  						3 => '3',
  						4 => '4',
  					),
  					'default_value' => array(
  						1 => '1',
  					),
  					'allow_null' => 0,
  					'multiple' => 0,
  					'ui' => 0,
  					'return_format' => 'value',
  					'ajax' => 0,
  					'placeholder' => '',
  				),
  			),
  		),
	),
	'min' => '',
	'max' => '',
);

 ?>
