<?php
$fields =  array(
	'key' => 'layout_logo_grid_'.$posttype,
	'name' => 'logo_grid_'.$posttype,
	'label' => 'Logo Carousel',
	'display' => 'block',
	'sub_fields' => array(
		array(
			'key' => 'field_logo_grid_headline_'.$posttype,
			'label' => 'Headline',
			'name' => 'logo_grid_headline',
			'type' => 'text',
			'instructions' => 'Enter a headline for this block.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_logo_grid_relationships_'.$posttype,
			'label' => 'Partner Logos',
			'name' => 'partner_logos',
			'type' => 'relationship',
			'post_type' => 'partner',
			'instructions' => 'Choose the partner logos you want to display',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'partner',
				1 => 'client',
			),
			'taxonomy' => '',
			'filters' => array('search', 'post_type'),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'id',
		),

		// array(
		// 	'key' => 'field_logo_grid_repeater_'.$posttype,
		// 	'label' => 'Logos',
		// 	'name' => 'logo_grid_repeater',
		// 	'type' => 'repeater',
		// 	'instructions' => 'Add a logo to this block.',
		// 	'required' => 0,
		// 	'conditional_logic' => 0,
		// 	'wrapper' => array(
		// 		'width' => '',
		// 		'class' => '',
		// 		'id' => '',
		// 	),
		// 	'collapsed' => '',
		// 	'min' => 1,
		// 	'max' => 50,
		// 	'layout' => 'block',
		// 	'button_label' => '+ Add Another Logo',
		// 	'sub_fields' => array(
		// 		array(
		// 			'key' => 'field_logo_grid_logo_'.$posttype,
		// 			'label' => 'Logo',
		// 			'name' => 'logo_grid_logo',
		// 			'type' => 'image',
		// 			'instructions' => 'Select a logo to add',
		// 			'required' => 0,
		// 			'conditional_logic' => 0,
		// 			'wrapper' => array(
		// 				'width' => '30',
		// 				'class' => '',
		// 				'id' => '',
		// 			),
		// 			'return_format' => 'array',
		// 			'preview_size' => 'thumbnail',
		// 			'library' => 'all',
		// 			'min_width' => '',
		// 			'min_height' => '',
		// 			'min_size' => '',
		// 			'max_width' => '',
		// 			'max_height' => '',
		// 			'max_size' => '',
		// 			'mime_types' => '',
		// 		),
		// 		array(
		// 			'key' => 'field_logo_grid_alt_text_'.$posttype,
		// 			'label' => 'Alt Text',
		// 			'name' => 'logo_grid_alt_text',
		// 			'type' => 'text',
		// 			'instructions' => '',
		// 			'required' => 0,
		// 			'conditional_logic' => 0,
		// 			'wrapper' => array(
		// 				'width' => '30',
		// 				'class' => '',
		// 				'id' => '',
		// 			),
		// 			'default_value' => '',
		// 			'placeholder' => '',
		// 			'prepend' => '',
		// 			'append' => '',
		// 			'maxlength' => '',
		// 		),
		// 		array(
		// 			'key' => 'field_logo_grid_link_'.$posttype,
		// 			'label' => 'Link',
		// 			'name' => 'logo_grid_link',
		// 			'type' => 'link',
		// 			'instructions' => 'Enter a link for this logo.',
		// 			'required' => 0,
		// 			'conditional_logic' => 0,
		// 			'wrapper' => array(
		// 				'width' => '30',
		// 				'class' => '',
		// 				'id' => '',
		// 			),
		// 			'return_format' => 'array',
		// 		),
		// 	),
		// ),
	),
	'min' => '',
	'max' => '',
);

?>
