<?php
$fields =  array(
	'key' => 'layout_blog_list_grid_'.$posttype,
	'name' => 'blog_list_grid_'.$posttype,
	'label' => 'Blog List or Grid',
	'display' => 'block',
	'sub_fields' => array(
    array(
      'key' => 'field_blog_list_grid_headline_'.$posttype,
      'label' => 'Blog Headline',
      'name' => 'headline',
      'type' => 'text',
      'filters' => '',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '66',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Blog',
    ),
    array(
			'key' => 'field_blog_list_grid_category_id_'.$posttype,
			'label' => 'Blog Category',
			'name' => 'category_id',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'select',
			'allow_null' => 1,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array(
			'key' => 'field_blog_list_grid_layout_style_'.$posttype,
			'label' => 'Layout Style',
			'name' => 'layout_style',
			'type' => 'radio',
      'layout' => 'horizontal',
      'choices' => array(
        'list' => 'List',
        'grid' => 'Grid',
      ),
			'filters' => '',
			'instructions' => 'Choose a layout style to display the three most recent blog posts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
    array(
			'key' => 'field_blog_list_grid_padding_top_'.$posttype,
			'label' => 'Padding Top',
			'name' => 'pad_top',
			'type' => 'select',
      'choices' => array(
        0 => '0',
        1 => '1',
        2 => '2',
        3 => '3',
        4 => '4',
      ),
      'default_value' => array(
        0 => 1,
      ),
      'allow_null' => 0,
			'filters' => '',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
    array(
      'key' => 'field_blog_list_grid_padding_bot_'.$posttype,
      'label' => 'Padding Bottom',
      'name' => 'pad_bot',
      'type' => 'select',
      'choices' => array(
        0 => '0',
        1 => '1',
        2 => '2',
        3 => '3',
        4 => '4',
      ),
      'default_value' => array(
        0 => 1,
      ),
      'allow_null' => 0,
      'filters' => '',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
    ),
	),
	'min' => '',
	'max' => '',
);

//return $fields;
?>
