<?php

$fields =  array(
	'key' => 'layout_blog_grid_cat_filter_'.$posttype,
	'name' => 'blog_grid_cat_filter_'.$posttype,
	'label' => 'Blog Grid with Category Filter',
	'display' => 'block',
	'sub_fields' => array(
			array(
				'key' => 'blog_grid_cat_filter_content_'.$posttype,
				'label' => 'Block Content',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
					'key' => 'field_blog_grid_cat_filter_headline_'.$posttype,
					'label' => 'Subscribe Text',
					'name' => 'headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
			array(
					'key' => 'field_blog_grid_cat_filter_link_text_'.$posttype,
					'label' => 'Subscribe Button Text',
					'name' => 'link_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
			array(
					'key' => 'field_blog_grid_cat_filter_link_'.$posttype,
					'label' => 'Button Link',
					'name' => 'button_link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'return' => 'id',
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
				array(
					'key' => 'field_blog_grid_cat_filter_padding_'.$posttype,
					'label' => 'Background Settings',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_blog_grid_cat_filter_padding_top_'.$posttype,
					'label' => 'Padding Top',
					'name' => 'blog_grid_cat_filter_padding_top',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						0 => '0',
						1 => '1',
						2 => '2',
						3 => '3',
						4 => '4',
					),
					'default_value' => array(
						0 => 2,
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_blog_grid_cat_filter_padding_bot_'.$posttype,
					'label' => 'Padding Bottom',
					'name' => 'blog_grid_cat_filter_padding_bot',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						0 => '0',
						1 => '1',
						2 => '2',
						3 => '3',
						4 => '4',
					),
					'default_value' => array(
						0 => 2,
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
	),
	'min' => '',
	'max' => '',
);

 ?>
