<?php
$fields =  array(
	'key' => 'layout_one_col_text_'.$posttype,
	'name' => 'one_col_text_'.$posttype,
	'label' => 'One Column Text',
	'display' => 'block',
	'sub_fields' => array(
		array(
				'key' => 'field_one_col_block_settings_'.$posttype,
				'label' => 'Block Content',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
		),
		array(
			'key' => 'field_one_col_txt_headline_'.$posttype,
			'label' => 'Headline',
			'name' => 'one_col_txt_headline',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '75',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_one_col_text_center_text_'.$posttype,
			'label' => 'Center Text',
			'name' => 'one_col_text_center_text',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => 'Center Text Horizontally',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_one_col_txt_sub_head_'.$posttype,
			'label' => 'Sub Headline',
			'name' => 'one_col_txt_sub_head',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_one_col_txt_text_'.$posttype,
			'label' => 'Main Text',
			'name' => 'one_col_txt_text',
			'type' => 'wysiwyg',
			'instructions' => 'Enter text for this one column text block.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_one_col_txt_button_text_'.$posttype,
			'label' => 'Button Text',
			'name' => 'one_col_txt_button_text',
			'type' => 'text',
			'instructions' => 'Enter text to display a button.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_one_col_txt_button_link_'.$posttype,
			'label' => 'Button Link',
			'name' => 'one_col_txt_button_link',
			'type' => 'link',
			'instructions' => 'Choose a link for the button',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 1,
		),


		array(
			'key' => 'field_bg_op_tab_'.$posttype,
			'label' => 'Background Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_one_col_img_txt_bg_options_'.$posttype,
			'label' => 'Background Options',
			'name' => 'one_col_img_txt_bg_options',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_one_col_bg_type_'.$posttype,
					'label' => 'Background Type',
					'name' => 'background_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'color' => 'Solid Color',
						'image' => 'Background Image',
						'video' => 'Background Video',
					),
					'default_value' => array(
						'color' => 'Solid Color',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_one_col_bg_img_'.$posttype,
					'label' => 'Background Image',
					'name' => 'one_col_bg_img',
					'type' => 'image_crop',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_one_col_bg_type_'.$posttype,
								'operator' => '==',
								'value' => 'image',
							),
						),
						array(
							array(
								'field' => 'field_one_col_bg_type_'.$posttype,
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'crop_type' => 'hard',
					'target_size' => 'ex-large',
					'width' => '',
					'height' => '',
					'preview_size' => 'thumbnail',
					'force_crop' => 'yes',
					'save_in_media_library' => 'yes',
					'retina_mode' => 'no',
					'save_format' => 'object',
					'library' => 'all',
				),
				array(
					'key' => 'field_one_col_background_video_webm_'.$posttype,
					'label' => 'Background Video .webm',
					'name' => 'background_video_webm',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_one_col_bg_type_'.$posttype,
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'webm',
				),
				array(
					'key' => 'field_one_col_background_video_mp4_'.$posttype,
					'label' => 'Background Video .mp4',
					'name' => 'background_video_mp4',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_one_col_bg_type_'.$posttype,
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
				array(
					'key' => 'field_one_col_bg_color',
					'label' => 'Background Color',
					'name' => 'one_col_bg_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_one_col_bg_filter',
					'label' => 'Background Filter',
					'name' => 'one_col_bg_filter',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_one_col_bg_type_'.$posttype,
								'operator' => '!=',
								'value' => 'color',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'none' => 'No Filter',
						'white' => 'Light',
						'black' => 'Dark',
					),
					'default_value' => array(
						0 => 'none',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_one_col_text_color_'.$posttype,
					'label' => 'Text Color',
					'name' => 'one_col_text_color',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'white' => 'Light',
						'black' => 'Dark',
					),
					'default_value' => array(
						0 => 'black',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_one_col_bg_parallax_'.$posttype,
					'label' => 'Parallax',
					'name' => 'bg_parallax',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_one_col_bg_type_'.$posttype,
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'no-parallax' => 'Parallax Off',
						'parallax' => 'Parallax On',
					),
					'default_value' => array(
						0 => 'no-parallax',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_one_col_bg_parallax_speed_'.$posttype,
					'label' => 'Parallax Speed',
					'name' => 'bg_parallax_speed',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_one_col_bg_parallax_'.$posttype,
								'operator' => '==',
								'value' => 'parallax',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'3' => 'Fastest',
						'2' => 'Fast',
						'1' => 'Normal',
						'0.5' => 'Slow',
						'0.25' => 'Slowest',
					),
					'default_value' => array(
						'1' => 'Slow',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_one_col_text_padding_top_'.$posttype,
					'label' => 'Padding Top',
					'name' => 'one_col_text_padding_top',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '12',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						0 => '0',
						1 => '1',
						2 => '2',
						3 => '3',
						4 => '4',
					),
					'default_value' => array(
						0 => 2,
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_one_col_text_padding_bot_'.$posttype,
					'label' => 'Padding Bottom',
					'name' => 'one_col_text_padding_bot',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '13',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						0 => '0',
						1 => '1',
						2 => '2',
						3 => '3',
						4 => '4',
					),
					'default_value' => array(
						0 => 2,
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_one_col_text_margin_'.$posttype,
					'label' => 'Margin',
					'name' => 'one_col_text_margin',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						0 => '0',
						1 => '1',
						2 => '2',
						3 => '3',
						4 => '4',
					),
					'default_value' => array(
						0 => 0,
					),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_one_col_animation_settings_tab_'.$posttype,
			'label' => 'Animation Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_one_col_text_animation_settings_'.$posttype,
			'label' => 'Animation Settings',
			'name' => 'animation_settings',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_one_col_text_headline_anim_'.$posttype,
					'label' => 'Headline Animation',
					'name' => 'headline_animation',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'fadeIn' => 'Fade In',
						'fadeInUp' => 'Fade In Up',
						'fadeInDown' => 'Fade In Down',
						'fadeInLeft' => 'Fade In Left',
						'fadeInRight' => 'Fade In Right',
						'jackInTheBox' => 'Jack In The Box',
					),
					'default_value' => array(
					),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_one_col_text_text_anim_'.$posttype,
					'label' => 'Text Animation',
					'name' => 'text_animation',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'fadeIn' => 'Fade In',
						'fadeInUp' => 'Fade In Up',
						'fadeInDown' => 'Fade In Down',
						'fadeInLeft' => 'Fade In Left',
						'fadeInRight' => 'Fade In Right',
						'jackInTheBox' => 'Jack In The Box',
					),
					'default_value' => array(
					),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_one_col_text_button_anim_'.$posttype,
					'label' => 'Button Animation',
					'name' => 'button_animation',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'fadeIn' => 'Fade In',
						'fadeInUp' => 'Fade In Up',
						'fadeInDown' => 'Fade In Down',
						'fadeInLeft' => 'Fade In Left',
						'fadeInRight' => 'Fade In Right',
						'jackInTheBox' => 'Jack In The Box',
					),
					'default_value' => array(
					),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
	),
	'min' => '',
	'max' => '',
);

//return $fields;
?>
