<?php
$fields =  array(
	'key' => 'layout_testimonial_rotator_'.$posttype,
	'name' => 'testimonial_rotator_'.$posttype,
	'label' => 'Testimonial Rotator',
	'display' => 'block',
	'sub_fields' => array(
		array(
			'key' => 'field_testimonial_rotator_headline_'.$posttype,
			'label' => 'Rotator Headline',
			'name' => 'testimonial_rotator_headline',
			'type' => 'text',
			'filters' => '',
			'post_type' => 'testimonial',
			'instructions' => 'Enter a headline for this testimonial rotator.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		// array(
		// 	'key' => 'field_testimonial_icon_image_'.$posttype,
		// 	'label' => 'Image',
		// 	'name' => 'testimonial_icon_image',
		// 	'type' => 'image',
		// 	'instructions' => 'Upload or select an image for the left column of this block.',
		// 	'required' => 0,
		// 	'wrapper' => array(
		// 		'width' => '',
		// 		'class' => '',
		// 		'id' => '',
		// 	),
		// 	'return_format' => 'array',
		// 	'preview_size' => 'thumbnail',
		// 	'library' => 'all',
		// 	'min_width' => '',
		// 	'min_height' => '',
		// 	'min_size' => '',
		// 	'max_width' => '',
		// 	'max_height' => '',
		// 	'max_size' => '',
		// 	'mime_types' => '',
		// ),
		array(
			'key' => 'field_testimonial_rotator_relationships_'.$posttype,
			'label' => 'Choose Testimonial',
			'name' => 'testimonial_rotator_relationships',
			'type' => 'relationship',
			'filters' => '',
			'post_type' => 'testimonial',
			'instructions' => 'Choose the names of the testimonials you would like to feature in this rotator block.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'min' => '',
	'max' => '',
);

//return $fields;
?>
